[package]
name = "timer-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.5"
rodio = "0.17.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"